### ISSUE TITLE
Login to golf.se using HTTPS

### ISSUE THREAD

**Issue by dentarg** [cheif/golfstats#3]
At https://github.com/cheif/golfstats/blob/ec1c6841f7e4e80dd3b95772bc46724ac555cdb8/golfse.rb#L19 I think we can use `https://www9.golf.se/...`

**Comment by dentarg** [comment]
I haven't submitted a PR yet, because locally I get a weird `OpenSSL::SSL::SSLError` I haven't figured out yet.

``` ruby
OpenSSL::SSL::SSLError - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed:
    /Users/dentarg/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:923:in `connect'
    /Users/dentarg/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
    /Users/dentarg/.rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
    /Users/dentarg/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:923:in `connect'
    /Users/dentarg/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
    /Users/dentarg/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:858:in `start'
    /Users/dentarg/.gem/ruby/2.2.2/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
    /Users/dentarg/.gem/ruby/2.2.2/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'
    /Users/dentarg/.gem/ruby/2.2.2/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
    /Users/dentarg/.gem/ruby/2.2.2/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:259:in `fetch'
    /Users/dentarg/.gem/ruby/2.2.2/gems/mechanize-2.7.3/lib/mechanize.rb:440:in `get'
    /Users/dentarg/Dropbox/code/shared/golfstats/golfse.rb:20:in `login'
    /Users/dentarg/Dropbox/code/shared/golfstats/golfse.rb:14:in `initialize'
    /Users/dentarg/Dropbox/code/shared/golfstats/models.rb:18:in `new'
    /Users/dentarg/Dropbox/code/shared/golfstats/models.rb:18:in `scrape'
    /Users/dentarg/Dropbox/code/shared/golfstats/web.rb:23:in `block in <top (required)>'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/rack-1.5.2/lib/rack/logger.rb:15:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/rack-1.5.2/lib/rack/chunked.rb:43:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
    /Users/dentarg/.gem/ruby/2.2.2/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
    /Users/dentarg/.rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
    /Users/dentarg/.rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
    /Users/dentarg/.rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
127.0.0.1 - - [13/Jul/2015 21:33:44] "POST /createCal/ HTTP/1.1" 500 185678 0.2895
```
